### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by guer0125** [guer0125/events-calendar#2]
hey

so markbot is asking for .list-group or .list-group-inline but im not sure where these goes.

also, how do i arrange the width and height of the cells and the numbers on the left top 

last thing, i don't know if the way i am pushing the 1 and 2 to the right is the right way. do i add a grid/unit system instead. or would both ways be ok?
 
thank you

@muxlowc

**Comment by muxlowc** [comment]
@guer0125 
1) instead of having your event items a simply` <p>` tags, you'll actually want to use `<ul>` and `<li>`s (even if theres only one event/li) - which is where your "list-group"

2) The numbers are simply aligning to the right (there should be a class on your typografier to do this)

3) For the width/height: you should only have to set a height , which will be placed on the tbody td (meaning all of the cells inside of your tbody)

4) You won't need a grid for this one, since the table should be doing most of the heavy lifting. Rather than using pad-t or pad-b, you might want to try: push-1-4 text-right 

You could also put a <div> inside your <td>s like so:
```
          <td>
            <div class="day text-right bold mega push-1-4">1</div>
          </td>
```

**Comment by guer0125** [comment]
Hi, 

just one more thing, markbot says my Merriweather font is missing. but it is there. how can i fix this?

**Comment by muxlowc** [comment]
@guer0125 try putting this into your html:

  `<link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">`

Google fonts has changed their html code a bit, so this is an older one that should work
